---
    - name: Install ansible-galaxy collection install community.general
      shell: ansible-galaxy collection install community.general
    - name: Sleep for 180 seconds and continue with play 
      wait_for: 
        timeout: 90
      delegate_to: localhost
    - name: Install plugins for jenkins
      community.general.jenkins_plugin:
        name: "{{ item }}"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_passw }}"
        url: "{{ jenkins_url }}"
        with_dependencies: yes
      with_items:
       - github
       - golang
       - Pipeline
       - nexus-artifact-uploader
       - ssh
       - ssh-agent
       - ssh-credentials
       - SSH-Build-Agents
       - ssh-steps
       - workflow-durable-task-step
       - pipeline-utility-steps
       - pipeline-stage-view
       - ssh-steps
       - pipeline-stage-step
       - docker-plugin
       - docker-pipeline
       - docker-workflow
       - docker-build-step
      ignore_errors: yes
