# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

#  config.ssh.username = "vagrant"
#  config.ssh.password = "vagrant"
#  config.ssh.insert_key = false
#  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
#        sudo setsebool -P httpd_unified 1
	sudo apt update
	apt remove gnupg
	apt install --reinstall gnupg2 -y
	apt install -y dirmngr
	sudo apt install -y lxc lxc-templates
	sudo iptables-restore /vagrant/ip_rul
	sudo cp /vagrant/default.conf /etc/lxc/
	sudo cp /vagrant/lxc-net /etc/default/
	sudo systemctl restart lxc-net

	sudo lxc-create -n c1 -t download -- --dist centos --release 8-Stream --arch amd64 --keyserver hkp://keyserver.ubuntu.com
	sudo echo "lxc.net.0.ipv4.address = 10.0.3.10/24">>/var/lib/lxc/c1/config
	sudo echo "lxc.net.0.ipv4.gateway = 10.0.3.1">>/var/lib/lxc/c1/config
	sudo lxc-start -n c1
	sudo sleep 20s
	sudo lxc-attach -n c1 -- export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin
	sudo lxc-attach -n c1 -- yum update
	sudo lxc-attach -n c1 -- yum install mc -y
	sudo lxc-attach -n c1 -- yum install httpd -y
	sudo lxc-attach -n c1 -- systemctl enable httpd
	sudo lxc-attach -n c1 -- systemctl start httpd
	sudo lxc-attach -n c1 -- mkdir -p /var/www/static/html
	sudo lxc-attach -n c1 -- chmod -R 0755 /var/www/static/html
	sudo cp /vagrant/index.html /var/lib/lxc/c1/rootfs/var/www/static/html
	sudo lxc-attach -n c1 -- mkdir /etc/httpd/sites-available
	sudo lxc-attach -n c1 -- mkdir /etc/httpd/sites-enabled
	sudo cp /vagrant/static.conf /var/lib/lxc/c1/rootfs/etc/httpd/sites-available/
	sudo cp /vagrant/httpd.conf /var/lib/lxc/c1/rootfs/etc/httpd/conf/
	sudo lxc-attach -n c1 -- ln -s /etc/httpd/sites-available/static.conf /etc/httpd/sites-enabled/static.conf
	sudo lxc-attach -n c1 -- chcon -R --type=httpd_sys_rw_content_t /var/www/
	sudo lxc-attach -n c1 -- systemctl restart httpd
	echo "!!!***** READY *****!!!"

	sudo lxc-create -n c2 -t download -- --dist centos --release 8-Stream --arch amd64 --keyserver hkp://keyserver.ubuntu.com
	sudo echo "lxc.net.0.ipv4.address = 10.0.3.11/24">>/var/lib/lxc/c2/config
	sudo echo "lxc.net.0.ipv4.gateway = 10.0.3.1">>/var/lib/lxc/c2/config
	sudo lxc-start -n c2
	sudo sleep 20s
	sudo lxc-attach -n c2 -- export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin
	sudo lxc-attach -n c2 -- yum update
	sudo lxc-attach -n c2 -- yum install mc -y
	sudo lxc-attach -n c2 -- yum install httpd -y
	sudo lxc-attach -n c2 -- yum install php -y
	sudo lxc-attach -n c2 -- yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
	sudo lxc-attach -n c2 -- yum install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
	sudo lxc-attach -n c2 -- install -y php php-cli php-common
	sudo lxc-attach -n c2 -- systemctl enable httpd
	sudo lxc-attach -n c2 -- systemctl start httpd	
	sudo lxc-attach -n c2 -- mkdir -p /var/www/dynamic/html
	sudo lxc-attach -n c2 -- chmod -R 0755 /var/www/dynamic/html
	sudo cp /vagrant/index.php /var/lib/lxc/c2/rootfs/var/www/dynamic/html
	sudo lxc-attach -n c2 -- mkdir /etc/httpd/sites-available
	sudo lxc-attach -n c2 -- mkdir /etc/httpd/sites-enabled
	sudo cp /vagrant/dynamic.conf /var/lib/lxc/c2/rootfs/etc/httpd/sites-available/
	sudo cp /vagrant/httpd1.conf /var/lib/lxc/c2/rootfs/etc/httpd/conf/httpd.conf
	sudo lxc-attach -n c2 -- ln -s /etc/httpd/sites-available/dynamic.conf /etc/httpd/sites-enabled/dynamic.conf
	sudo lxc-attach -n c2 -- chcon -R --type=httpd_sys_rw_content_t /var/www/
	sudo lxc-attach -n c2 -- systemctl restart httpd
	echo "!!!***** COMPLETE *****!!!"
 SHELL
  
end
