# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ddd015/ubuntu2010"

  config.vm.network "forwarded_port", guest: 80, host: 50150
  config.vm.network "forwarded_port", guest: 81, host: 8081

  #config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"
  #config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "test2" do |test2|
   #test2.vm.network "private_network", ip: "192.168.56.4"
   test2.vm.provision "shell", inline: <<-SHELL
  	echo "!!!!!!!!!!!!!"
    sudo apt update
    sudo apt install ansible -y
    sudo ansible-playbook /vagrant/playbook.yml -i /vagrant/hosts
    ansible.become = true
   SHELL

  end
end
