---
   - name: Install build-essential default-jre
     apt:
       name: ['build-essential']
       state: latest
       update_cache: yes 

   - name: Download Nexus
     get_url:
       url: https://download.sonatype.com/nexus/3/nexus-3.38.1-01-unix.tar.gz
       checksum: md5:d3d2e8ebef0816f412b66fe7a374f923
       dest: /opt/nexus3.tar.gz

   - name: Create workdir
     file:
       path: /opt/nexus
       state: directory

   - name: Unpack Nexus
     unarchive:
       src: /opt/nexus3.tar.gz
       dest: /opt/nexus/

   - name: Find last release
     find:
       file_type: directory
       patterns: 'nexus*'
       path: /opt/nexus

     register: nexus_path
   - name: Create nexus symlink
     file:
       path: /opt/nexus/nexus
       state: link
       src: "{{ nexus_path.files[0]['path'] }}"
     when: nexus_path.matched > 0

   - name: Copy environment file
     copy:
       src: '/vagrant/roles/install_nexus/files/nexus-server'
       dest: /etc/default/nexus-server

   - name: Copy systemd file
     copy:
       src: /vagrant/roles/install_nexus/files/nexus.service
       dest: /etc/systemd/system/nexus.service

   - name: SystemD_Reload
     ansible.builtin.systemd:
       daemon_reload: yes

   - name: Start Nexus service
     systemd:
       name: nexus
       enabled: yes
       state: started