# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081
  
  config.vm.provision "shell", inline: <<-SHELL
	sudo apt update
	sudo apt install -y apache2
	sudo apt install -y libapache2-mod-php php php-cli php-mysql php-json php-opcache php-mbstring php-intl php-xml php-gd php-zip php-curl php-xmlrpc unzip
	sudo mkdir -p /var/www/static/
	sudo chmod -R 755 /var/www/static
	sudo mkdir -p /var/www/dynamic/
	sudo chmod -R 755 /var/www/dynamic
	sudo cp /vagrant/index.html /var/www/static/
	sudo cp /vagrant/index.php /var/www/dynamic/
	sudo cp /vagrant/static.conf /etc/apache2/sites-available/
	sudo cp /vagrant/dynamic.conf /etc/apache2/sites-available/
	sudo cp /vagrant/ports.conf /etc/apache2/
#echo "Listen 81">>/etc/apache2/ports.conf
	sudo a2dissite 000-default.conf
	sudo a2ensite static.conf
	sudo a2ensite dynamic.conf
	sudo systemctl restart apache2
#commit
   SHELL
	
  
end
