# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

#    config.ssh.username = "vagrant"
#    config.ssh.password = "vagrant"
#    config.ssh.insert_key = false 
    config.vm.synced_folder ".", "/vagrant", disable: false 
    config.vm.box = "generic/debian11"
  
    config.vm.define "nexus" do |nexus|
    nexus.vm.network "private_network", ip: "192.168.56.11"
    nexus.vm.hostname = "nexus"
    nexus.vm.provision :shell, inline: <<-SHELL
      timedatectl set-timezone Europe/Minsk
      apt-get update
      apt-get install -y sshpass python3-pip mc
      echo "y" | pip install ansible
      sudo ansible-playbook /vagrant/playbook.yml -i /vagrant/hosts
#      apt-get install -y git build-essential default-jre
    SHELL
    end
end