---
 - hosts: all
   #connection: local
   become: yes
   tasks:
      - name: Create folder
        file:
          path: "{{ item.dir }}"
          mode: "{{ item.prava }}"
          state: directory
        with_items:
         - {dir: '/var/www/static/html', prava: '0755'}
         - {dir: '/var/www/dynamic/html', prava: '0755'}
      - name: Copy conf files     
        copy:
          src: "{{ item.cfg }}"
          dest: /etc/httpd/conf.d/
        with_items:
         - {cfg: '/vagrant/stdyn.conf'}
      - name: Copy html and php files
        copy:
          src: "{{ item.f }}"
          dest: "{{ item.d }}"
        with_items:
         - {f: '/vagrant/index.html', d: '/var/www/static/html'}
         - {f: '/vagrant/index.php', d: '/var/www/dynamic/html'}
#      - name: "add info config httpd"
#        shell: "echo {{ item }} >> /etc/httpd/conf/httpd.conf"
#        loop:
#          - "Listen 81"
#        register: echo
      - name: add port 81 to config httpd
        lineinfile:
          path: /etc/httpd/conf/httpd.conf
          insertbefore: 'Listen 80'
          line: Listen 81
      - name: "Restart httpd"    
        service:
          name: httpd
          state: restarted
