---
#   - name: Download Nexus
#     get_url:
#       url: https://download.sonatype.com/nexus/3/nexus-3.38.1-01-unix.tar.gz
#       checksum: md5:d3d2e8ebef0816f412b66fe7a374f923
#       dest: /opt/nexus3.tar.gz
#   - name: Create workdir
#     file:
#       path: /opt/nexus
#       state: directory
#   - name: Unpack Nexus
#     unarchive:
#       src: /opt/nexus3.tar.gz
#       dest: /opt/nexus/
#   - name: Find last release
#     find:
#       file_type: directory
#       patterns: 'nexus*'
#       path: /opt/nexus
#     register: nexus_path
#   - name: Create nexus symlink
#     file:
#       path: /opt/nexus/nexus
#       state: link
#       src: "{{ nexus_path.files[0]['path'] }}"
#     when: nexus_path.matched > 0
#   - name: Copy environment file
#     template:
#       src: '/vagrant/roles/inst_nexus/files/nexus-server'
#       dest: /etc/default/nexus-server
#   - name: Copy systemd file
#     template:
#       src: /vagrant/roles/inst_nexus/files/nexus.service
#       dest: /etc/systemd/system/nexus.service
#   - name: SystemD_Reload
#     ansible.builtin.systemd:
#       daemon_reload: yes
#   - name: Start Nexus service
#     systemd:
#       name: nexus
#       enabled: yes
#       state: started
    - name: Install geerlingguy.java
      shell: |
        ansible-galaxy install geerlingguy.java
        ansible-galaxy install geerlingguy.apache
    - name: Git clone
      git:
        repo: 'https://github.com/ansible-ThoTeam/nexus3-oss.git'
        dest: '/srv/checkout'
    - name: Install jmespath
      pip:
        requirements: /srv/checkout/requirements.txt
    - name: Install build-essential default-jre
      apt:
        name: ['build-essential','default-jre']
        state: latest
        update_cache: yes
      


  