# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

#  config.ssh.username = "vagrant"
#  config.ssh.password = "vagrant"
#  config.ssh.insert_key = false 
#  config.vm.network "forwarded_port", guest: 80, host: 8080
#  config.vm.network "forwarded_port", guest: 81, host: 8081
  config.vm.synced_folder ".", "/vagrant", disable: false 
  config.vm.box = "generic/debian10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.define "dockertest" do |dockertest|
  dockertest.vm.network "private_network", ip: "192.168.56.141"
  dockertest.vm.hostname = "dockertest"
  dockertest.vm.provision :shell, inline: <<-SHELL
    apt-get update
    apt-get install -y sshpass docker.io docker-compose
    usermod -aG vagrant docker
    #cd /vagrant
    #sudo docker-compose up --build
    #sudo docker container start nexus
    
    #sudo docker container start jenkins
  SHELL
  end
end
