---
    - name: Install bottle python package
      pip:
        name: ['python-jenkins','lxml']
      notify:
       - Stop_Jenkins
    - name: Creat user folder
      file:
        path: /var/lib/jenkins/users/admin_17653030755750021651
        state: directory
    - name: Change jenkins.service
        lineinfile:
          path: /lib/systemd/system/jenkins.service
          regexp: '^Environment="JAVA_OPTS=-Djava.awt.headless=true"'
          line: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
    - name: Copy xml files to jenkis
      template:
        src: "{{ item.f }}"
        dest: "{{ item.d }}"
      with_items:
         - {f: '/vagrant/roles/conf_jenkins/files/config.xml', d: '/var/lib/jenkins/'}
         - {f: '/vagrant/roles/conf_jenkins/files/users/users.xml', d: '/var/lib/jenkins/users/'}
         - {f: '/vagrant/roles/conf_jenkins/files/users/admin_17653030755750021651/config.xml', d: '/var/lib/jenkins/users/admin_17653030755750021651/'}
    - name: Jenkins Skip startUp for MI change conf
      template:
        src: /vagrant/roles/conf_jenkins/templates/jenkins
        dest: /etc/default/jenkins
    - name: Delete file inintialAdminPassword  
      file:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        state: absent
      notify:
      - Start_Jenkins
    - name: Wait for Jenkins to start up
      uri:
        url: "{{ jenkins_url }}"
        status_code: 200
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_passw }}"
        force_basic_auth: yes
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 10
      delay: 5
      until: >
        'status' in jenkins_service_status and
        jenkins_service_status['status'] == 200