---
 - hosts: localhost
   become: true
   pre_tasks:
   - include_tasks: '/vagrant/install_open_jdk8.yml'
  
   vars:
    nexus_timezone: 'Europa/Minsk'
    nexus_admin_password: "admin123"
    nexus_anonymous_access: false
    httpd_setup_enable: false
    nexus_delete_default_repos: true
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
    nexus_roles:
      - id: uploader # maps to the LDAP group
        name: uploader
        description: All uploader
        privileges:
          - nx-repository-view-raw-word-cloud-build-add
          - nx-repository-view-raw-word-cloud-build-browse
          - nx-repository-view-raw-word-cloud-build-edit
#          - nx-repository-view-*-*-*
        roles: []
      - id: downloader # maps to the LDAP group
        name: downloader
        description: All downloader
        privileges:
          - nx-repository-view-*-*-*
        roles: []

    nexus_local_users:
      - username: uploader 
        first_name: uploader
        last_name: CI
        email: support@company.com
        password: "123"
        roles:
          - uploader 
      - username: downloader 
        first_name: downloader
        last_name: CI
        email: support@company.com
        password: "123"
        roles:
          - downloader 
     
    # Change nexus_config_raw to true for create raw repository
    nexus_config_raw: true
    nexus_repos_raw_hosted:
    - name: word-cloud-build
      version_policy: release
      write_policy: allow  # one of "allow", "allow_once" or "deny"
      strict_content_validation: false
     
   roles:
     - role: '/usr/share/ansible/roles/nexus3-oss'


   

   




     
