---
 - hosts: all
   become: true
   tasks:
#     - name: Install puppetserver and update
#       yum:
#         name:
#           - build-essential
#           - python-selinux 
#           - mc
#         state: latest
#         update_cache: true 
     - name: Off SeLinux
       selinux:
         state: disabled 
     - name: Add Puppet repo
       yum:
         name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
         disable_gpg_check: yes
     - name: Add mappings to /etc/hosts
       blockinfile:
         path: /etc/hosts
         block: |
           {{ item.ip }} {{ item.name }}
         marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
       loop:
         - { name: master, ip: 192.168.56.5 }
         - { name: slave1, ip: 192.168.56.6 }
         - { name: slave2, ip: 192.168.56.7 } 
     - name: Stop firewall
       service:
         name: firewalld
         state: stopped
 - hosts: master
   become: true
   tasks:
     - name: Install puppetserver and update
       yum:
         name:
           - puppetserver
           - git 
         state: latest
         update_cache: true 
     - name: Install r10k
       shell: /opt/puppetlabs/puppet/bin/gem install r10k
     - name: Set r10k directory config
       file:
         path: /etc/puppetlabs/r10k
         state: directory
     - name: file r10k.yaml
       file:
         path: /etc/puppetlabs/r10k/r10k.yaml
         state: touch
     - name: Set config r10k
       copy: 
         dest: /etc/puppetlabs/r10k/r10k.yaml
         content: |
           :cashedir: '/var/cache/r10k'
           :sources:
             :my-org:
               remote: 'https://github.com/ddd015/minecraft.git'
               basedir: '/etc/puppetlabs/code/environments'
     - name: Set puppet server conf
       ini_file:
         path: /etc/puppetlabs/puppet/puppet.conf
         section: "{{ item.sect }}"
         option: "{{ item.option }}"
         value: "{{ item.value }}"
       with_items:
        - { sect: "main", option: "server", value: "master" }
        - { sect: "main", option: "certname", value: "master" }
        - { sect: "main", option: "environment", value: "production" }
        - { sect: "master", option: "dns_alt_names", value: "master" }
        - { sect: "server", option: "autosign", value: "true" }
        - { sect: "server", option: "server", value: "master" }
        - { sect: "agent", option: "server", value: "master" }
        - { sect: "agent", option: "runinterval", value: "1m" }
     - name: Config puppetserver memory 
       lineinfile:
         path: /etc/sysconfig/puppetserver
         regexp: '^JAVA_ARGS='
         insertbefore: '^JAVA_ARGS='
         line: 'JAVA_ARGS="-Xms256m -Xmx256m -Djrubby.logger.class-com.pupetlabs.jruby_utils.jruby.Slf4jLogger"'
         state: present
     - name: Start puppetserver
       service:
         name: puppetserver
         state: restarted
         enabled: yes
     - name: Restart puppetserver
       service:
         name: puppetserver
         state: restarted
     - name: Stop httpd and disable autorun
       service:
         name: httpd
         state: stopped
         enabled: no
     - name: Creates a cron file under /etc/cron.d
       cron:
         name: r01k autoupdate
         minute: "*/2"
         user: root
         job: "/opt/puppetlabs/puppet/bin/r10k deploy environment -p"
     - name: Enable puppe–µ service agent
       service:
         name: puppet
         state: started
         enabled: true
