# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ddd015/centos8"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false 
  config.vm.synced_folder ".", "/vagrant" 
#  config.vm.provider "virtualbox" do |vb|
#    vb.memory = 512
#    vb.cpus   = 1
#  end

  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.56.5"
    master.vm.hostname = "minecraft"
    master.vm.provider("virtualbox") { |vb| vb.memory = 2048 }
    master.vm.provision :shell, inline: <<-SHELL
#      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
#      yum install -y vim mc
#      yum install -y --downloadonly puppetserver git
      sudo yum update
      sudo yum install ansible -y
      sudo ansible-playbook /vagrant/playbook.yml -i /vagrant/hosts
    SHELL
  end
end
