---
 - hosts: nexus
   become: true
   pre_tasks:
   - include_tasks: '/vagrant/roles/install_nexus/tasks/install_open_jdk8.yml'
  
   vars:
    nexus_timezone: 'Europa/Minsk'
    nexus_admin_password: "admin123"
    nexus_anonymous_access: true
    httpd_setup_enable: false
    nexus_delete_default_repos: true
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit
    nexus_roles:
      - id: Developpers # maps to the LDAP group
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
          - company-project-deploy
        roles: []
    nexus_local_users:
      - username: jenkins # used as key to update
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        password: "jenkins"
        roles:
          - Developpers # role ID here
    nexus_blobstores:
      - name: company-artifacts
        path: /var/nexus/blobs/company-artifacts
  
    # Change nexus_config_raw to true for create raw repository
    nexus_config_raw: true
    nexus_repos_raw_hosted:
    - name: world-cloud-build
      version_policy: release
      write_policy: allow  # one of "allow", "allow_once" or "deny"
     
   roles:
     - role: '/vagrant/roles/nexus3-oss'

 - hosts: jenkins
   tasks:
   become: true
   roles:
     - role: '/vagrant/roles/install_jenkins' 

   




     
