---
 - hosts: stading
   become: true
   tasks:
     - name: Create folder
       file:
         path: /opt/wordcloud
         state: directory
         owner: vagrant
         group: vagrant
     - name: Copy service file 
       copy:  
         src: /vagrant/wordcloud.service
         dest:  /etc/systemd/system/wordcloud.service
     - name: SystemD_Reload
       ansible.builtin.systemd:
         daemon_reload: yes 

 - hosts: production
   become: true
   tasks:
     - name: Install jq
       apt:
         name: ['jq']
         state: latest
         update_cache: yes
     - name: Create folder
       file:
         path: /opt/wordcloud
         state: directory
         owner: vagrant
         group: vagrant
     - name: Copy service file 
       copy:  
         src: /vagrant/wordcloud.service
         dest:  /etc/systemd/system/wordcloud.service
     - name: SystemD_Reload
       ansible.builtin.systemd:
         daemon_reload: yes 

 - hosts: nexus
   become: true
   pre_tasks:
   - include_tasks: '/vagrant/roles/install_nexus/tasks/install_open_jdk8.yml'
  
   vars:
    nexus_timezone: 'Europa/Minsk'
    nexus_admin_password: "admin123"
    nexus_anonymous_access: true
    httpd_setup_enable: false
    nexus_delete_default_repos: true
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit
    nexus_roles:
      - id: Developpers # maps to the LDAP group
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
          - company-project-deploy
          - nx-repository-view-*-*-*
        roles: []
    nexus_local_users:
      - username: vagrant # used as key to update
        first_name: vagrant
        last_name: CI
        email: support@company.com
        password: "123"
        roles:
          - Developpers # role ID here
#    nexus_blobstores:
#      - name: company-artifacts
#        path: /var/nexus/blobs/company-artifacts
      
    # Change nexus_config_raw to true for create raw repository
    nexus_config_raw: true
    nexus_repos_raw_hosted:
    - name: world-cloud-build
      version_policy: release
      write_policy: allow  # one of "allow", "allow_once" or "deny"
      strict_content_validation: false
     
   roles:
     - role: '/vagrant/roles/nexus3-oss'

 - hosts: jenkins
   tasks:
   become: true
   roles:
     - role: '/vagrant/roles/install_jenkins' 

   

   




     
