---
   - name: Stop Jenkins
     systemd:
       name: jenkins
       state: stopped
       daemon_reload: true
   - name: Start Jenkins
     systemd:
       name: jenkins
       state: started
       daemon_reload: true
