---
   - name: Stop Jenkins
     service:
       name: jenkins
       state: stopped
   - name: Start Jenkins
     service:
       name: jenkins
       state: started
   - name: Restart SystemD
     systemd:
       daemon_reload: yes