FROM golang:1.16

#COPY playbook.yml /vagrant/
#COPY install_open_jdk8.yml /vagrant/
#COPY roles-nexus /usr/share/ansible/roles
RUN git clone https://github.com/ddd015/word-cloud-generator.git
RUN cd word-cloud-generator
RUN export GOPATH=$WORKSPACE/go
RUN export PATH="$PATH:$(go env GOPATH)/bin"               
RUN go get github.com/tools/godep
RUN go get github.com/smartystreets/goconvey
RUN go get github.com/GeertJohan/go.rice/rice  
RUN go get github.com/wickett/word-cloud-generator/wordyapi
RUN go get github.com/gorilla/mux
RUN sed -i "s/1.DEVELOPMENT/1.$BUILD_NUMBER/g" /go/word-cloud-generator/static/version
RUN cd ..
RUN GOOS=linux GOARCH=amd64 go build -o ./artifacts/word-cloud-generator -v 
RUN gzip -f /go/word-cloud-generator/artifacts/word-cloud-generator

EXPOSE 8888

CMD /go/word-cloud-generator/artifacts/word-cloud-generator 