version: '3.5'

services:
  nexus:
    build:
      context: ./nexus/ 
      dockerfile: Dockerfile
    image: nexus
    container_name: nexus
    network_mode: host

  jenkins:
    build:
      context: ./jenkins/
      dockerfile: Dockerfile
    image: jenkins
    privileged: true
    container_name: jenkins
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins_vol:/var/lib/jenkins/workspace/
    network_mode: host

volumes:
  jenkins_vol:

