version: '3.5'

services:
#  nexus:
#    build:
#      context: ./nexus/ #file path Doskerfile.multi
#      dockerfile: Dockerfile
#    image: nexus
#    container_name: nexus
##    volumes:
##    - ./nexus/roles-nexus:/usr/share/ansible/roles
#    ports:
#    - 8081:8081
#    networks:
#    - nginx-net

  jenkins:
    build:
      context: ./jenkins/ #file path Doskerfile.multi
      dockerfile: Dockerfile
    image: jenkins
    privileged: true
    container_name: jenkins
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8080:8080
    networks:
    - nginx-net

#  nginx:
#    image: nginx
#    container_name: nginx
#    ports:
#    - "8080:8080"
#    - "8081:8081"
#    networks:
#    - nginx-net
#    depends_on:
#    - nexus
#    - jenkins
#    volumes:
#    - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  nginx-net: {}







#    networks:
#      - bridge

#networks:
#  bridge:
#    driver: bridge
#    ipam:
#     config:
#       - subnet: 172.10.10.0/24
#         gateway: 172.10.10.1
#         aux_addresses:
#          nexus: 172.10.10.2
          

