# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disable: false 
  config.vm.box = "generic/debian10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.define "dockertest" do |dockertest|
  dockertest.vm.network "private_network", ip: "192.168.56.140"
  dockertest.vm.hostname = "dockertest"
  dockertest.vm.provision :shell, inline: <<-SHELL
    apt-get update
    apt-get install -y sshpass docker.io docker-compose -y
    usermod -aG docker vagrant
    cd /vagrant
    sudo docker-compose up --build
  SHELL
  end
end
