---
 - hosts: all
   become: true
   tasks:
     - name: Add Puppet repo
       yum:
         name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
         disable_gpg_check: yes
     - name: Add mappings to /etc/hosts
       blockinfile:
         path: /etc/hosts
         block: |
           {{ item.ip }} {{ item.name }}
         marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
       loop:
         - { name: master.local, ip: 192.168.56.5 }
         - { name: slave1.local, ip: 192.168.56.6 }
         - { name: slave2.local, ip: 192.168.56.7 } 
     - name: update cashe
       shell: sudo yum update -y
     - name: Stop firewall
       service:
         name: firewalld
         state: stopped
 - hosts: master
   become: true
   tasks:
     - name: Install puppetserver
       yum:
         name: puppetserver
         state: present 
     - name: Install r10k
       shell: /opt/puppetlabs/puppet/bin/gem install r10k
     - name: Install git
       yum:
         name: git
         state: latest
     - name: Set r10k directory config
       file:
         path: /etc/puppetlabs/r10k
         state: directory
     - name: file r10k.yaml
       file:
         path: //etc/puppetlabs/r10k/r10k.yaml
         state: touch
     - name: Set config r10k
       copy: 
         dest: /etc/puppetlabs/r10k/r10k.yaml
         content: |
           :cashedir: '/var/cache/r10k'
           :sources:
             :my-org:
               remote: 'git@github.com:ddd015/puppet.git'
               basedir: '/etc/puppetlabs/code/environments'
     - name: Set puppet server conf
       ini_file:
         path: /etc/puppetlabs/puppet/puppet.conf
         section: agent
         option: "{{ item.option }}"
         value: "{{ item.value }}"
       with_items:
        - { option: "server", value: "master.local" }
        - { option: "certname", value: "master.local" }
        - { option: "environment", value: "production" }
     - name: Config puppetserver memory 
       lineinfile:
         path: /etc/sysconfig/puppetserver
         regexp: '^JAVA_ARGS='
         insertbefore: '^JAVA_ARGS='
         line: 'JAVA_ARGS="-Xms256m -Xmx256m -Djrubby.logger.class-com.pupetlabs.jruby_utils.jruby.Slf4jLogger"'
         state: present
     - name: Set puppet master autosign
       ini_file:
         path: /etc/puppetlabs/puppet/puppet.conf
         section: server
         option: "autosign"
         value: "true"
     - name: Set puppet master server
       ini_file:
         path: /etc/puppetlabs/puppet/puppet.conf
         section: server
         option: "server"
         value: "master.local"
     - name: Start puppetserver
       service:
         name: puppetserver
         state: restarted
         enabled: yes
     - name: Restart puppetserver
       service:
         name: puppetserver
         state: restarted
 - hosts: slave1
   become: true
   tasks:
     - name: Install puppet agent
       yum:
         pkg: puppet-agent
         state: present
         update_cache: yes
     - name: Set puppet agent conf
       ini_file:
         path: /etc/puppetlabs/puppet/puppet.conf
         section: agent
         option: "{{ item.option }}"
         value: "{{ item.value }}"
       with_items:
        - { option: "server", value: "master.local" }
        - { option: "runinterval", value: "1m" }
     - name: Enable puppe–µ service
       service:
         name: puppet
         state: started
         enabled: true
     - name: restart puppet
       become: true
       service:
         name: puppet
         state: restarted
 - hosts: slave2
   become: true
   tasks:
     - name: Install puppet agent
       yum:
         pkg: puppet-agent
         state: present
         update_cache: yes
     - name: Set puppet agent conf
       ini_file:
         path: /etc/puppetlabs/puppet/puppet.conf
         section: agent
         option: "{{ item.option }}"
         value: "{{ item.value }}"
       with_items:
         - { option: "server", value: "master.local" }
         - { option: "runinterval", value: "1m" }
     - name: Enable pupper service
       service:
         name: puppet
         state: started
         enabled: true
     - name: restart puppet
       become: true
       service:
         name: puppet
         state: restarted