# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ddd015/centos8"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1
  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.56.5"
    master.vm.hostname = "master.puppet"
    master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
    master.vm.provision :shell, inline: <<-SHELL
      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      yum install -y vim mc
      yum install -y --downloadonly puppetserver git
      sudo ansible-playbook /vagrant/playbook.yml -i /vagrant/hosts
      ansible.become = true
    SHELL
  end

  config.vm.define "slave1.puppet" do |slave1|
    slave1.vm.network "private_network", ip: "192.168.56.6"
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.provision :shell, inline: <<-SHELL
      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      yum install -y vim mc
      yum install -y --downloadonly puppet-agent
    SHELL
  end

  config.vm.define "slave1.puppet" do |slave2|
    slave2.vm.network "private_network", ip: "192.168.56.7"
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.provision :shell, inline: <<-SHELL
      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      yum install -y vim mc
      yum install -y --downloadonly puppet-agent
    SHELL
  end
end
