---
    - name: Install ansible galaxy jenkins
      apt:
        pkg:
        - jenkins
        - mc
        - python3-pip
        state: latest
    - name: Install bottle python package
      pip:
        name: ['python-jenkins','lxml']
      notify:
       - Stop Jenkins
    - name: Creat user folder
      file:
        path: /var/lib/jenkins/users/admin_17653030755750021651
        state: directory
    - name: Copy xml files to jenkis
      template:
        src: "{{ item.f }}"
        dest: "{{ item.d }}"
      with_items:
         - {f: '/vagrant/roles/jenkins/files/config.xml', d: '/var/lib/jenkins/'}
         - {f: '/vagrant/roles/jenkins/files/users/users.xml', d: '/var/lib/jenkins/users/'}
         - {f: '/vagrant/roles/jenkins/files/users/admin_17653030755750021651/config.xml', d: '/var/lib/jenkins/users/admin_17653030755750021651/'}
    - name: Jenkins Skip startUp for MI change conf
      template:
        src: /vagrant/roles/jenkins/templates/jenkins
        dest: /etc/default/jenkins
    - name: Jenkins Skip startUp for Jenkins.service change conf
      template:
        src: /vagrant/roles/jenkins/templates/jenkins.service
        dest: /lib/systemd/system/jenkins.service
      notify:
      - Restart SystemD
    - name: Delete file inintialAdminPassword  
      file:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        state: absent
      notify:
      - Start Jenkins
    - name: Wait for Jenkins to start up
      uri:
        url: "{{ jenkins_url }}"
        status_code: 200
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_passw }}"
        force_basic_auth: yes
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 10
      delay: 5
      until: >
        'status' in jenkins_service_status and
        jenkins_service_status['status'] == 200
    - name: Install plugins for jenkins
      jenkins_plugin:
        name: "{{ item }}"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_passw }}"
        url: "{{ jenkins_url }}"
        with_dependencies: yes
      with_items:
       - git
       - github
       - goland
       - Pipeline    
    - name: Create a jenkins job using basic authentication
      jenkins_job:
        config: "{{ lookup('file', 'templates/dobuild.xml') }}"
        name: dobiuild
        password: "{{ jenkins_passw }}"
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"
        state: present
    - name: Create a jenkins build using basic authentication
      jenkins_build:
        name: "dobiuild"
        build_number: 1.01
        state: present
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_passw }}"
        url: "{{ jenkins_url }}"

