---
   - name: Stop_Jenkins
     ansible.builtin.systemd:
       name: jenkins
       state: stopped
     become: yes
   - name: Start_Jenkins
     ansible.builtin.systemd:
       name: jenkins
       state: started
     become: yes
   - name: SystemD_Reload
     ansible.builtin.systemd:
       daemon_reload: yes
     become: yes
